#!/usr/bin/with-contenv bash

if [[ $(uname -m) = "x86_64" ]] && [[ ! -d "/dev/kvm" ]]; then
    echo "┌───────────────────────────────────────────────────────────────────────────────┐"
    echo "│                    You need to enable to enable QEMU. Run:                    │"
    echo "│                                                                               │"
    echo "│     docker run --rm --privileged multiarch/qemu-user-static --reset -p yes    │"
    echo "│                                                                               │"
    echo "│                                  on the host                                  │"
    echo "└───────────────────────────────────────────────────────────────────────────────┘"
    sleep infinity
fi
