#!/usr/bin/with-contenv bash
# shellcheck shell=bash

docker pull docker.io/moby/buildkit:buildx-stable-1
HOME=/config docker buildx rm container >/dev/null 2>&1
HOME=/config docker buildx create --driver docker-container --name container --bootstrap >/dev/null 2>&1
docker image prune -f >/dev/null 2>&1

USER_NAME=${USER_NAME:-jenkins}
lsiown -R "${USER_NAME}:${USER_NAME}" /config/.docker
